engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - src/**
  - "**.js"
  - "**.scss"
  - "**.css"
exclude_paths:
- bin/**/*
- blueprints/**/*
- build/**/*
- config/**/*
- coverage/**/*
- node_modules/**/*
- server/**/*
- tests/**/*
