export default {
  ANNUALLY: 'ANNUALLY',
  FIRST_TUESDAY_OF_THE_MONTH: 'FIRST_TUESDAY_OF_THE_MONTH',
  MONTHLY: 'MONTHLY',
  TWICE_A_MONTH: 'TWICE_A_MONTH',
  EVERY_OTHER_WEEK: 'EVERY_OTHER_WEEK',
  WEEKLY: 'WEEKLY'
}
